// <auto-generated />
using Demo3DAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo3DAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115103438_AddRoleAndSeedData")]
    partial class AddRoleAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo3DAPI.Models.PlayerAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("PlayerAccounts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FullName = "Admin",
                            Password = "$2a$11$eBFOGWYh8ztLXOf/8Dae3O7xruSaZdu9JFzuzeIIST5boNz/lkZ9S",
                            RoleID = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Demo3DAPI.Models.PlayerCharacter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlayerAccountID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlayerAccountID");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("Demo3DAPI.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Demo3DAPI.Models.PlayerAccount", b =>
                {
                    b.HasOne("Demo3DAPI.Models.Role", "Role")
                        .WithMany("PlayerAccounts")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Demo3DAPI.Models.PlayerCharacter", b =>
                {
                    b.HasOne("Demo3DAPI.Models.PlayerAccount", "PlayerAccount")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("Demo3DAPI.Models.PlayerAccount", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Demo3DAPI.Models.Role", b =>
                {
                    b.Navigation("PlayerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
